# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cec6c1cf23ffedbf963710dfb000c39f"
application_url = "https://statutory-regulations-arctic-entrepreneur.trycloudflare.com"
embedded = true
name = "app-test"
handle = "app-test-690"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://statutory-regulations-arctic-entrepreneur.trycloudflare.com/auth/callback",
  "https://statutory-regulations-arctic-entrepreneur.trycloudflare.com/auth/shopify/callback",
  "https://statutory-regulations-arctic-entrepreneur.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
